name: "godot-build"
on: push

env:
  GODOT_VERSION: 4.0.3
  EXPORT_NAME: test-project
  ITCHIO_USERNAME: ${{ vars.ITCHIO_USERNAME }}
  ITCHIO_GAME: ${{ vars.ITCHIO_GAME }}
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
  
jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [Linux, Windows_Desktop, Web]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.5.0
        with:
          name: example
          preset: ${{ matrix.platform }}
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}