name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 4.0.3
  EXPORT_NAME: test-project
  
jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.0.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot --headless -v --export-release "Web" ../build/web/index.html
      - name: Upload Artifact to Itch with Butler
        run: | 
          wget -O butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          butler push ./build/web $ITCHIO_USERNAME/$ITCHIO_GAME:web



#  export-windows:
#    name: Windows Export
#    runs-on: ubuntu-20.04
#    container:
#      image: barichello/godot-ci:4.0.3
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          lfs: true
#      - name: Setup
#        run: |
#          mkdir -v -p ~/.local/share/godot/templates
#          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
#      - name: Windows Build
#        run: |
#          mkdir -v -p build/windows
#          godot --headless -v --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v1
#        with:
#          name: windows
#          path: build/windows
#  export-linux:
#    name: Linux Export
#    runs-on: ubuntu-20.04
#    container:
#      image: barichello/godot-ci:4.0.3
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          lfs: true
#      - name: Setup
#        run: |
#          mkdir -v -p ~/.local/share/godot/templates
#          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
#      - name: Linux Build
#        run: |
#          mkdir -v -p build/linux
#          godot --headless -v --export-release "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v1
#        with:
#          name: linux
#          path: build/linux
#  export-mac:
#    name: Mac Export
#    runs-on: ubuntu-20.04
#    container:
#      image: barichello/godot-ci:4.0.3
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          lfs: true
#      - name: Setup
#        run: |
#          mkdir -v -p ~/.local/share/godot/templates
#          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
#      - name: Mac Build
#        run: |
#          mkdir -v -p build/mac
#          godot --headless -v --export-release "Mac OSX" ../build/mac/$EXPORT_NAME.zip
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v1
#        with:
#          name: mac
#          path: build/mac
